/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>

/* Header for class test_zml_com_myndk_AbstractPlayerActivity */

#ifndef _Included_test_zml_com_myndk_AbstractPlayerActivity
#define _Included_test_zml_com_myndk_AbstractPlayerActivity

#include "../../../../../../../Android/sdk/ndk-bundle/sysroot/usr/include/jni.h"

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_zml_com_myndk_AbstractPlayerActivity
 * Method:    open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_test_zml_com_myndk_AbstractPlayerActivity_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     test_zml_com_myndk_AbstractPlayerActivity
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_test_zml_com_myndk_AbstractPlayerActivity_getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     test_zml_com_myndk_AbstractPlayerActivity
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_test_zml_com_myndk_AbstractPlayerActivity_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     test_zml_com_myndk_AbstractPlayerActivity
 * Method:    getFrameRate
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_test_zml_com_myndk_AbstractPlayerActivity_getFrameRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     test_zml_com_myndk_AbstractPlayerActivity
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_test_zml_com_myndk_AbstractPlayerActivity_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
