/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_zml_com_myndk_OpenGLPlayerActivity */

#ifndef _Included_test_zml_com_myndk_OpenGLPlayerActivity
#define _Included_test_zml_com_myndk_OpenGLPlayerActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_zml_com_myndk_OpenGLPlayerActivity
 * Method:    init
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_test_zml_com_myndk_OpenGLPlayerActivity_init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     test_zml_com_myndk_OpenGLPlayerActivity
 * Method:    initSurface
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_test_zml_com_myndk_OpenGLPlayerActivity_initSurface
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     test_zml_com_myndk_OpenGLPlayerActivity
 * Method:    render
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_test_zml_com_myndk_OpenGLPlayerActivity_render
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     test_zml_com_myndk_OpenGLPlayerActivity
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_test_zml_com_myndk_OpenGLPlayerActivity_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
