/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>

/* Header for class test_zml_com_myndk_BitmapPlayerActivity */

#ifndef _Included_test_zml_com_myndk_BitmapPlayerActivity
#define _Included_test_zml_com_myndk_BitmapPlayerActivity

#include "../../../../../../../Android/sdk/ndk-bundle/sysroot/usr/include/jni.h"

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_zml_com_myndk_BitmapPlayerActivity
 * Method:    render
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_test_zml_com_myndk_BitmapPlayerActivity_render
        (JNIEnv *,jclass,jlong,jobject);


#ifdef __cplusplus
}
#endif
#endif
