/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/bitmap.h>
/* Header for class test_zml_com_myndk_JNITest */

#ifndef _Included_test_zml_com_myndk_JNITest
#define _Included_test_zml_com_myndk_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_zml_com_myndk_JNITest
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test_zml_com_myndk_JNITest_getVersion
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_test_zml_com_myndk_JNITest_sendMessage
  (JNIEnv *, jclass,jstring);

#ifdef __cplusplus
}
#endif
#endif
